development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: pfm_development
  pool: 5
  username: root
  password:
  socket: <%= ['/var/lib/mysql/mysql.sock', '/var/run/mysqld/mysqld.sock', '/tmp/mysql.sock'].detect{ |socket| File.exist?(socket) } %>

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: pfm_test
  pool: 5
  username: root
  password:
  socket: <%= ['/var/lib/mysql/mysql.sock', '/var/run/mysqld/mysqld.sock', '/tmp/mysql.sock'].detect{ |socket| File.exist?(socket) } %>

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: budget247_prod
  pool: 5
  username: budget247_prod
  password: Aeraegee7DiP8ved1uh5
  socket: <%= ['/var/lib/mysql/mysql.sock', '/var/run/mysqld/mysqld.sock', '/tmp/mysql.sock'].detect{ |socket| File.exist?(socket) } %>
